### ISSUE TITLE
macro too many continuation

### ISSUE THREAD

**Issue by equation-group** [Inf0secRabbit/BadAssMacros#2]
The generated vba macro is very long, the error is too many line continuation , not able to manually add the macro in the doc file.

**Comment by Inf0secRabbit** [comment]
> The generated vba macro is very long, the error is too many line continuation , not able to manually add the macro in the doc file.

Hey, thanks for pointing this out, we are already aware of it. Will release the fix soon :)

**Comment by eqn-grp** [comment]
will wait for the release.
